src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Form\DataTransformer\CollectionToArrayTransformer;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ParticipantRepository")
 * @UniqueEntity(fields={"mail"}, message="There is already an account with this mail")
 */
class Participant implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\Length(
     *      min = 2,
     *      max = 30,
     *      minMessage = "Minimum : {{ limit }} characters long",
     *      maxMessage = "Maximum :  {{ limit }} characters"
     * )
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\Length(
     *      min = 3,
     *      max = 30,
     *      minMessage = "Minimum : {{ limit }} characters long",
     *      maxMessage = "Maximum :  {{ limit }} characters"
     * )
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     * @Assert\Length(
     *      min = 9,
     *      max = 15,
     *      minMessage = "Minimum : {{ limit }} characters long",
     *      maxMessage = "Maximum :  {{ limit }} characters"
     * )
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Length(
     *      min = 8,
     *      max = 100,
     *      minMessage = "Minimum : {{ limit }} characters long",
     *      maxMessage = "Maximum :  {{ limit }} characters"
     * )
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mot_de_passe;

    /**
     * @ORM\Column(type="boolean")
     */
    private $admin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Site", inversedBy="participants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $site;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sortie", mappedBy="organisateur")
     */
    private $ses_sorties;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Sortie", mappedBy="inscrits")
     */
    private $sorties;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo_url;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Groupe", mappedBy="proprietaireGroupe", orphanRemoval=true)
     */
    private $groupes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Groupe", mappedBy="participants")
     */
    private $groupesPresence;

    public function __construct()
    {
        $this->setAdmin(false);
        $this->ses_sorties = new ArrayCollection();
        $this->sorties = new ArrayCollection();
        $this->groupes = new ArrayCollection();
        $this->groupesPresence = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = str_replace(" ","", $telephone);

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = strtolower($mail);

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): self
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    public function getAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSesSorties(): Collection
    {
        return $this->ses_sorties;
    }

    public function addSesSorty(Sortie $sesSorty): self
    {
        if (!$this->ses_sorties->contains($sesSorty)) {
            $this->ses_sorties[] = $sesSorty;
            $sesSorty->setOrganisateur($this);
        }

        return $this;
    }

    public function removeSesSorty(Sortie $sesSorty): self
    {
        if ($this->ses_sorties->contains($sesSorty)) {
            $this->ses_sorties->removeElement($sesSorty);
            // set the owning side to null (unless already changed)
            if ($sesSorty->getOrganisateur() === $this) {
                $sesSorty->setOrganisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->addInscrit($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->sorties->contains($sorty)) {
            $this->sorties->removeElement($sorty);
            $sorty->removeInscrit($this);
        }

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photo_url;
    }

    public function setPhotoUrl(?string $photo_url): self
    {
        $this->photo_url = $photo_url;

        return $this;
    }
    /**
     * Loads the user for the given username.
     *
     * This method must return null if the user is not found.
     *
     * @param string $username The username
     *
     * @param ParticipantRepository $userFactory
     * @return Participant
     */
    public function loadUserByUsername($username, ParticipantRepository $userFactory)
    {
        return($userFactory->findOneBy(array('mail'=>$username)));
    }

    /**
     * String representation of object
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        // TODO: Implement serialize() method.
    }

    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        // TODO: Implement unserialize() method.
    }

    /**
     * Returns the roles granted to the user.
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        if($this->getAdmin()){
            $roles = ['ROLE_ADMIN'];
        }else{
            $roles = ['ROLE_USER'];
        }
        return $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string|null The encoded password if any
     */
    public function getPassword()
    {
        return $this->getMotDePasse();
    }


    public function setPassword($mot_de_passe)
    {
        $this->setMotDePasse($mot_de_passe);
    }


    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->getMail();
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Groupe[]
     */

templates/participant/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau participant{% endblock %}

{% block body %}
<div class="container">
    <h1>Nouveau participant</h1>

    <a class="btn btn-light" href="{{ path('participant_list') }}"> < Retour</a>
    <hr>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <div style="display: flex; justify-content: flex-end;">
        <input class="btn btn-primary" type="submit">
    </div>
    {{ form_end(form) }}


</div>
{% endblock %}
  {% block javascripts %}
      <script>

          // Assuming you have an input element in your HTML with the class .myInput
          var inputTel = document.querySelector('.input-phone')

          var telMask = vanillaTextMask.maskInput({
              inputElement: inputTel,
              mask: phoneMask,

          });
      </script>
  {% endblock %}

templates/participant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ participant.pseudo }}{% endblock %}

{% block body %}


    <div class="container px-lg-5 border">


        <div class="form-group">
            {{ form_start(registrationForm) }}
            <h1 class="text-center mt-2">
                {{ form_widget(registrationForm.pseudo, { 'attr' : { 'class' : 'form-control bigTopFormField'} } ) }}
            </h1>

            <div class="row">
                {% if participant.photoUrl != null %}

                    <div class="col-lg-4 col-md-12 text-center p-1">
                        <img  class="img-fluid"  src="{{ participant.photoUrl }}" />
                    </div>
                {% endif %}

                <table class="table
                {% if participant.photoUrl != null %}
                col-lg-8 col-md-12
                {% else %}
                col-12
                {% endif %}
        ">

                    <tr>
                        <th scope="row">Prénom</th>
                        <td>{{ form_widget(registrationForm.prenom, { 'attr' : { 'class' : 'form-control m-2'} } ) }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Nom</th>
                        <td>{{ form_widget(registrationForm.nom, { 'attr' : { 'class' : 'form-control  m-2'} } ) }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Email</th>
                        <td>{{ form_widget(registrationForm.mail, { 'attr' : { 'class' : 'form-control  m-2'} } ) }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Téléphone</th>
                        <td>{{ form_widget(registrationForm.telephone, { 'attr' : { 'class' : 'form-control m-2 input-phone'} } ) }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Ville de rattachement</th>
                        <td>{{ form_widget(registrationForm.site, { 'attr' : { 'class' : 'form-control m-2'} } ) }}</td>
                    </tr>
                </table>
            </div>
            <div style="display: flex; justify-content: flex-end;">
                <a class="btn btn-primary" style="margin: 0 10px;" href="{{ path('participant_list',{id: participant.id}) }}">Retour</a>
                <button class="btn btn-primary">Valider</button>
            </div>
            {{ form_end(registrationForm) }}
        </div>
    </div>

    {% if(errors is defined) %}
    <div class="container m-4 mx-auto">
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{error | raw}}
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="container px-lg-5 border mt-lg-4">
        <div class="form-group">
            <h1 class="text-center mt-2">
               Modifier le mot de passe
            </h1>
            {{ form_start(passwordForm) }}
            <div class="row">
                <table class="table col-12">

                    <tr>
                        <th scope="row">Nouveau mot de passe</th>
                        <td>{{ form_widget(passwordForm.plainPassword1, { 'attr' : { 'class' : 'form-control m-2'} } ) }}</td>
                    </tr>
                    <tr>
                        <th scope="row">confirmation du nouveau mot de passe</th>
                        <td>{{ form_widget(passwordForm.plainPassword2, { 'attr' : { 'class' : 'form-control  m-2'} } ) }}</td>
                    </tr>
                </table>
            </div>
            <div style="display: flex; justify-content: flex-end;">
                <button class="btn btn-primary">Modifier</button>
            <div>
            {{ form_end(passwordForm) }}
        </div>
    </div>

{% endblock %}


        {% block javascripts %}
            <script>

                // Assuming you have an input element in your HTML with the class .myInput
                var inputTel = document.querySelector('.input-phone')

                var telMask = vanillaTextMask.maskInput({
                    inputElement: inputTel,
                    mask: phoneMask,

                });
            </script>
        {% endblock %}

templates/participant/edit_infos.html.twig
{% extends 'participant/edit_layout.html.twig' %}

{% block title %}{{ participant.pseudo }}{% endblock %}

{% block formblock %}

                <div class="form-group">
                    {{ form_start(registrationForm) }}
                    <h1 class="text-center mt-2">
                        {{ form_widget(registrationForm.pseudo, { 'attr' : { 'class' : 'form-control bigTopFormField'} } ) }}
                    </h1>

                    <div class="row">
                        {% if participant.photoUrl != null %}

                            <div class="col-lg-4 col-md-12 text-center p-1">
                                <img  class="img-fluid"  src="{{ participant.photoUrl }}" />
                            </div>
                        {% endif %}

                        <table class="table
                {% if participant.photoUrl != null %}
                col-lg-8 col-md-12
                {% else %}
                col-12
                {% endif %}
        ">

                            <tr>
                                <th scope="row">Prénom</th>
                                <td>{{ form_widget(registrationForm.prenom, { 'attr' : { 'class' : 'form-control m-2'} } ) }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Nom</th>
                                <td>{{ form_widget(registrationForm.nom, { 'attr' : { 'class' : 'form-control  m-2'} } ) }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Email</th>
                                <td>{{ form_widget(registrationForm.mail, { 'attr' : { 'class' : 'form-control  m-2'} } ) }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Téléphone</th>
                                <td>{{ form_widget(registrationForm.telephone, { 'attr' : { 'class' : 'form-control m-2 input-phone'} } ) }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Ville de rattachement</th>
                                <td>{{ form_widget(registrationForm.site, { 'attr' : { 'class' : 'form-control m-2'} } ) }}</td>
                            </tr>
                        </table>
                    </div>
                    <a class="btn btn-primary" href="{{ path('participant_show',{id: participant.id}) }}">Retour</a>
                    <button class="btn btn-primary">Valider</button>
                    {{ form_end(registrationForm) }}
                </div>



{% endblock %}

  {% block javascripts %}
      <script>

          // Assuming you have an input element in your HTML with the class .myInput
          var inputTel = document.querySelector('.input-phone')

          var telMask = vanillaTextMask.maskInput({
              inputElement: inputTel,
              mask: phoneMask,

          });
      </script>
  {% endblock %}

templates/participant/edit_layout.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ participant.pseudo }}{% endblock %}

{% block body %}

    <div class="container pt-4">
        <div class="row">
            <div class="col-lg-4 col-sm-12 col-md-12">
                {% include 'participant/edit_menu.html.twig' %}
            </div>
            <div class="col-lg-8 col-sm-12 col-md-12">

                {% block formblock %}{% endblock%}
                </div>
        </div>
    </div>

    {% if(errors is defined) %}
        <div class="container m-4 mx-auto">
            {% for error in errors %}
                <div class="alert alert-danger" role="alert">
                    {{error | raw}}
                </div>
            {% endfor %}
        </div>
    {% endif %}

{% endblock %}

templates/participant/edit_menu.html.twig
<div class="list-group">
    <a href="{{ path('participant_edit_mon_pofil') }}" class="list-group-item {% if app.request.attributes.get('_route') == 'participant_edit_mon_pofil' %}active{% endif %}">Informations</a>
    <a href="{{ path('participant_edit_password') }}" class="list-group-item {% if app.request.attributes.get('_route') == 'participant_edit_password' %}active{% endif %}">Mot de passe</a>
    <a href="{{ path('participant_edit_photo') }}" class="list-group-item {% if app.request.attributes.get('_route') == 'participant_edit_photo' %}active{% endif %}">Photo de profil</a>
</div>

templates/participant/edit_password.html.twig
{% extends 'participant/edit_layout.html.twig' %}


{% block formblock %}

                <div class="form-group">
                    <h1 class="text-center mt-2">
                        Modifier le mot de passe
                    </h1>
                    {% if error is defined %}
                        {% if error != null %}
                        <div class="alert alert-danger" role="alert">{{ error | raw }}</div>
                        {% endif %}
                    {% endif %}
                    {{ form_start(passwordForm) }}
                    <div class="row">
                        <table class="table col-12">

                            <tr>
                                <th scope="row">Nouveau mot de passe</th>
                                <td>{{ form_widget(passwordForm.plainPassword1, { 'attr' : { 'class' : 'form-control m-2'} } ) }}</td>
                            </tr>
                            <tr>
                                <th scope="row">confirmation du nouveau mot de passe</th>
                                <td>{{ form_widget(passwordForm.plainPassword2, { 'attr' : { 'class' : 'form-control  m-2'} } ) }}</td>
                            </tr>
                        </table>
                    </div>
                    <button class="btn btn-primary">Modifier</button>
                    {{ form_end(passwordForm) }}
                </div>

{% endblock %}


        {% block javascripts %}

        {% endblock %}

templates/participant/edit_photo.html.twig
{% extends 'participant/edit_layout.html.twig' %}


{% block formblock %}

    <h2>Photo de profil</h2>
    <div class="row">
        <div class="col-lg-4 col-sm-12 col-md-12">
            <img src="{{ app.user.photoUrl }}"  class="img-fluid"/>
        </div>
        <div class="col-lg-8 col-sm-12 col-md-12">

            <div id="drag-drop-area"></div>
        </div>
    </div>

{% endblock %}


        {% block javascripts %}


            <script src="https://transloadit.edgly.net/releases/uppy/v1.4.0/uppy.min.js"></script>
            <script>
                var uppy = Uppy.Core({
                    restrictions: {
                        maxFileSize: 1000000,
                        maxNumberOfFiles: 1,
                        minNumberOfFiles: 1,
                        allowedFileTypes: ['image/*']
                    }
                });
                var Dashboard = Uppy.Dashboard;
                uppy.use(Uppy.Dashboard, {
                    inline: true,
                    target: '#drag-drop-area'
                });
                // uppy.use(Uppy.GoogleDrive, { target: Dashboard, companionUrl: 'https://companion.uppy.io' });
                // uppy.use(Uppy.Dropbox, { target: Dashboard, companionUrl: 'https://companion.uppy.io' });
                // uppy.use(Uppy.Instagram, { target: Dashboard, companionUrl: 'https://companion.uppy.io' });
                // uppy.use(Uppy.Url, { target: Dashboard, companionUrl: 'https://companion.uppy.io' });
                uppy.use(Uppy.Webcam, { target: Dashboard });
                uppy.use(Uppy.XHRUpload, {
                    endpoint: '{{path('participant_upload_photo')}}'
                });
                uppy.on('complete', (result) => {
                    console.log('Upload complete! We’ve uploaded these files:', result.successful)
                    document.location.reload();
                });
                {#uppy.use(Uppy.Tus, { endpoint: '{{path('participant_upload_photo')}}' });#}
            </script>
        {% endblock %}

templates/participant/import.html.twig
{% extends 'base.html.twig' %}

{% block title %}Import participants{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">Import participants</h1>

    <a class="btn btn-light" href="{{ path('participant_list') }}"> < Retour</a>
    <hr>
    <div class="alert alert-primary" role="alert">
        Veuillez selectionner un fichier CSV ou JSON
    </div>
    {{ form_start(form) }}
        <div style="display: flex; flex-direction: row">
            {{ form_label(form.fichier) }}
            {{ form_widget(form.fichier) }}
        </div>
        <div style="display: flex; justify-content: flex-end; margin-top: 10px;">
            {{ form_widget(form.valider) }}
        </div>
    {{ form_end(form) }}
</div>
{% endblock %}

templates/participant/import_confirm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Import participants{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">Import participants</h1>

    <a class="btn btn-primary" href="{{ path('participant_list') }}">Retour</a>
    <table class="table">
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Pseudo</th>
            <th>Email</th>
            <th>Téléphone</th>
            <th>Admin</th>
            <th>Actif</th>
            <th>Site</th>
            <th>Photo</th>
            <th></th>
        </tr>
        {% for p in valid %}
        <tr>
            <td>{{ p.nom }}</td>
            <td>{{ p.prenom }}</td>
            <td>{{ p.pseudo }}</td>
            <td>{{ p.mail }}</td>
            <td>{{ p.telephone }}</td>
            <td>{{ p.admin ? 'Oui':'Non' }}</td>
            <td>{{ p.actif ? 'Oui' :'Non' }}</td>
            <td>{{ p.site.nom }}</td>
            <td>{{ p.photoUrl }}</td>
            <td><span class="badge badge-pill badge-primary">Valide</span></td>
        </tr>
        {% endfor %}
        {% for p in invalid %}
            <tr>
                <td>{{ p.nom }}</td>
                <td>{{ p.prenom }}</td>
                <td>{{ p.pseudo }}</td>
                <td>{{ p.mail }}</td>
                <td>{{ p.telephone }}</td>
                <td>{{ p.admin ? 'Oui':'Non' }}</td>
                <td>{{ p.actif ? 'Oui' :'Non' }}</td>
                <td>{{ p.site.nom }}</td>
                <td>{{ p.photoUrl }}</td>
                <td>
                    <span class="badge badge-pill badge-danger">Invalide</span></td>
            </tr>
        {% endfor %}
    </table>
    <form method="post" action="{{ path('participant_import_validate') }}">
        <input type="hidden" name="users" value="{{ users }}">
        <input type="submit" value="Valider" class="btn-primary btn">
    </form>
</div>
{% endblock %}

templates/participant/passwordRecover.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <h1 class="container">Récupération du compte</h1>
    {{form_start(form.mail) }}
    <div class="container">
        {% if error is defined %}
            {% if error != null %}
                <div class="alert alert-danger" role="alert">{{ error | raw }}</div>
            {% endif %}
        {% endif %}
        <h4 class="text-secondary">Entrez l'adresse Email du participant</h4>
        <div class="form-group">
            <div class="form-group mb-2">
                {{ form_widget(form.mail, { 'attr' : { 'class' : 'form-control'} } ) }}
            </div>
        </div>
        {{ form_row(form._token) }}
        <button class="btn btn-lg btn-primary" type="submit" value="Enregistrer" id="Enregistrer">Au secours</button>
            <!doctype html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport"
                      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
                <meta http-equiv="X-UA-Compatible" content="ie=edge">
                <title>Document</title>
            </head>
            <body>
            
            </body>
            </html>
        </button>
    </div>
    {{ form_end(form.mail) }}
{% endblock %}

templates/participant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ participant.pseudo }}{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">
        {{ participant.pseudo }}
        {% if(isOwner != false) %}
            (votre profil)
        {% endif %}
    </h1>

    <div class="row">
        {% if participant.photoUrl != null %}

            <div class="col-lg-4 col-md-12 text-center p-1">
                <img  class="img-fluid"  src="{{ participant.photoUrl }}" />
            </div>
        {% endif %}

        <table class="table
        {% if participant.photoUrl != null %}
        col-lg-8 col-md-12
        {% else %}
        col-12
        {% endif %}
">

            <tr>
                <th scope="row">Prénom</th>
                <td>{{ participant.prenom }}</td>
            </tr>
            <tr>
                <th scope="row">Nom</th>
                <td>{{participant.nom}}</td>
            </tr>
            <tr>
                <th scope="row">Téléphone</th>
                <td>{{participant.telephone}}</td>
            </tr>
            <tr>
                <th scope="row">Email</th>
                <td>{{participant.mail}}</td>
            </tr>
            <tr>
                <th scope="row">Ville de rattachement</th>
                <td>{{participant.site.nom}}</td>
            </tr>

        </table>
    </div>
    <div style="display: flex; justify-content: flex-end;">
        <a class="btn btn-primary" style="margin: 0 10px" href="{{ path('participant_list') }}">Retour</a>
        {% if(isOwner != false) %}
            <a class="btn btn-primary" href="{{ path('participant_edit_mon_pofil') }}">Editer</a>
        {% elseif is_granted('ROLE_ADMIN') %}
                <a class="btn btn-primary" href="{{ path('participant_edit',{id:participant.id}) }}">Editer</a>
        {% endif %}
    </div>
</div>
{% endblock %}