src/Entity/Ville.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VilleRepository")
 */
class Ville
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Lieu", mappedBy="ville")
     */
    private $lieus;

    public function __construct()
    {
        $this->lieus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Lieu[]
     */
    public function getLieus(): Collection
    {
        return $this->lieus;
    }

    public function addLieus(Lieu $lieus): self
    {
        if (!$this->lieus->contains($lieus)) {
            $this->lieus[] = $lieus;
            $lieus->setVille($this);
        }

        return $this;
    }

    public function removeLieus(Lieu $lieus): self
    {
        if ($this->lieus->contains($lieus)) {
            $this->lieus->removeElement($lieus);
            // set the owning side to null (unless already changed)
            if ($lieus->getVille() === $this) {
                $lieus->setVille(null);
            }
        }

        return $this;
    }
}

src/Form/VilleType.php
<?php

namespace App\Form;

use App\Entity\Ville;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class VilleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class,['label' => 'Nom', 'constraints' => [ new NotBlank(['message' => 'Veuillez saisir un nom'])]])
            ->add('code_postal', TextType::class, ['label' => 'Code postal',
                'attr' => ['minlength' => '5', 'maxlength' => '5'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un code postal',
                    ]),
                    new Length([
                        'min' => 5,
                        'minMessage' => 'Le code postal doit faire {{ limit }} caractères',
                        // max length allowed by Symfony for security reasons
                        'max' => 5,
                        'maxMessage' => 'Le code postal doit faire {{ limit }} caractères',
                    ]),
                ],])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ville::class,
        ]);
    }
}

src/Controller/VilleController.php
<?php

namespace App\Controller;

use App\Repository\VilleRepository;
use App\Entity\Ville;
use App\Form\VilleType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Annotations\AnnotationReader;

class VilleController extends AbstractController
{
    /**
     * @Route("/admin/ville", name="ville")
     */
    public function index(VilleRepository $repo, EntityManagerInterface $em, Request $request)
    {
        $filtres['ville'] = $request->get('ville');
        $villes = $repo->findByfilterFields($filtres, $repo);

        return $this->render("ville/index.html.twig",
            [
                "villes" => $villes,
                "filtres" => $filtres,
            ]);
    }

    /**
     * @Route("/admin/ville/add", name="ville_add")
     */
    public function add(Request $request, EntityManagerInterface $em)
    {
        $ville = new Ville();
        //Creation du formulaire avec un objet vide
        $form = $this->createForm(VilleType::class, $ville);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            //Insert
            $em->persist($ville);
            $em->flush();

            return $this->redirectToRoute("ville", ["id" => $ville->getId()]);
        }

        return $this->render("ville/add.html.twig", ["villeForm" => $form->createView()]);
    }

    /**
     * @Route("/admin/ville/update/{id}", name="ville_update", requirements={"id":"\d+"})
     */
    public function update(Ville $ville, Request $request, EntityManagerInterface $em)
    {
        $form = $this->createForm(VilleType::class,$ville);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $em->persist($ville);
            $em->flush();

            $this->addFlash('success', 'Ville successfully updated!');
            return $this->redirectToRoute('ville');
        }

        return $this->render("ville/add.html.twig", ["villeForm" => $form->createView()]);
    }

    /**
     * @Route("/admin/ville/del/{id}", name="ville_del")
     */
    public function del(Ville $ville, EntityManagerInterface $em){
            $em->remove($ville);
            $em->flush();
            $this->addFlash("success", "Ville successfully deleted!");

        return $this->redirectToRoute('ville');
    }
}

templates/ville/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Add Ville!{% endblock %}

{% block body %}
    {%  if ville is defined and ville.id  %}
        <h1>Modifier une ville</h1>
    {%  else  %}
        <h1>Ajouter une ville</h1>
    {% endif %}
    <div class="container">
        {{ form_start(villeForm) }}
        {{ form_widget(villeForm) }}
        <a href="{{ path('ville') }}" class="btn btn-primary">Annuler</a>
        <button style="margin: 0 10px;" class="btn btn-primary" type="submit">Valider</button>
        {{ form_end(villeForm) }}
    </div>

{% endblock %}

templates/ville/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('/css/dataTable.css') }}">
{% endblock %}

{% block title %}Ville{% endblock %}

{% block body %}
    <style>

        .table tr td:not(:last-child), .table tr th:not(:last-child) {
            text-align: center;
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
            max-width: 0;
            font-size: 10pt;
            width: calc(100% / 5);
        }

        .table tr td:last-child {
            text-align: center;
            font-size: 10pt;
        }
    </style>
    <div class="container">
        <h2>Liste des villes
            <a class="btn btn-primary" title="Ajouter une ville" href="{{ path('ville_add') }}">
                <span class="fa fa-plus" aria-hidden="true"></span>
            </a>
        </h2>

        <table id="villeTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Ville</th>
                <th>Code postal</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody id="villesList">
            {% for ville in villes %}
                <tr>
                    <td>{{ ville.nom }}</td>
                    <td>{{ ville.codePostal }}</td>
                    <td style="width: 20%">
                        <a href="{{ path('ville_update', {'id' : ville.id}) }}"
                           class="badge badge-info">Modifier</a>
                        <a href="{{ path('ville_del', {'id' : ville.id})  }}"
                           class="badge badge-danger">Supprimer</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}
{% block javascripts %}
<script src="{{ asset('/js/dataTable.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('#villeTable').DataTable(
                {
                    "language": {
                        "url": "/js/frenchDataTable.json"
                    }
                }
            );
        });
    </script>
{% endblock javascripts %}